# Generated by Django 3.0 on 2021-11-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    database_operations = [migrations.AlterModelTable('Address', 'lettings_address'),
                           migrations.AlterModelTable('Letting', 'lettings_letting'),
                           migrations.AlterModelTable('Profile', 'profiles_profile'),
                           ]

    state_operations = [migrations.DeleteModel('Address'),
                        migrations.DeleteModel('Letting'),
                        migrations.DeleteModel('Profile'),
                        ]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
        ]
